/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bookrental;

import java.awt.Color;
import java.awt.Dimension;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Ali Hannoun & Ramazan Cinardere
 * 
 * 
 */

public class BookInfo extends javax.swing.JFrame {

    Book book;
    User user;
    
    public BookInfo(User obj, Book obj2) throws MalformedURLException {
        initComponents();
        setLocationRelativeTo(null);
       
        book = obj2;
        user = obj;
        
        jScrollPane1.setBorder(null);
        jTextArea_description.setBackground(new Color(0, 0, 0, 0));
        jTextArea_description.setLineWrap(true);
        jTextArea_description.setWrapStyleWord(true);
        jTextArea_description.setBorder(null);
        jLabel_title.setText(book.getTitle());
        jLabelRelease.setText(book.getreleaseYear());
        jLabelAuthor.setText(book.getAuthor());
        jLabelPrice.setText(book.getPrice());
        jLabelGenre.setText(book.getGenre());
        jLabelAgeRating.setText(book.getAgerating() + " Years");
        jLabelRating.setText(book.getRating());
       
        if(book.getLanguage2().equals("")){
            jLabelLanguage.setText(book.getLanguage());
        }else{
            jLabelLanguage.setText(book.getLanguage() + ", " + book.getLanguage2());
        }
        String description = book.getDescription();
       
        jTextArea_description.setText(description);
        jLabel_imgLink.setIcon(new ImageIcon(new URL(book.getImglink())));
        jLabel_imgLink.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_logo = new javax.swing.JLabel();
        jLabel_imgLink = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_genre = new javax.swing.JLabel();
        jLabel_ageRating = new javax.swing.JLabel();
        jLabel_rating = new javax.swing.JLabel();
        jLabel_description = new javax.swing.JLabel();
        jButton_buyBook = new javax.swing.JButton();
        jButton_return = new javax.swing.JButton();
        jLabel_language = new javax.swing.JLabel();
        jLabel_release = new javax.swing.JLabel();
        jLabel_author = new javax.swing.JLabel();
        jCombo_rating = new javax.swing.JComboBox();
        jButton_rateBook = new javax.swing.JButton();
        jLabelRelease = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelGenre = new javax.swing.JLabel();
        jLabelAgeRating = new javax.swing.JLabel();
        jLabelRating = new javax.swing.JLabel();
        jLabelLanguage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jLabel_price = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new Dimension(775,670));
        
        jLabel_title.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel_title.setText("Graphics under C");

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jLabel_logo.setText("jLabel2");

        jLabel_imgLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookLibrary.png"))); // NOI18N
        jLabel_imgLink.setText("jLabel1");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel_genre.setText("Genre:");

        jLabel_ageRating.setText("Age Rating:");

        jLabel_rating.setText("Rating:");

        jLabel_description.setText("Description:");

        jButton_buyBook.setText("Buy Book");
        jButton_buyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buyBookActionPerformed(evt);
            }
        });

        jButton_return.setText("Return");
        jButton_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_returnActionPerformed(evt);
            }
        });

        jLabel_language.setText("Language:");

        jLabel_release.setText("Release:");

        jLabel_author.setText("Author:");

        jCombo_rating.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "4", "3", "2", "1" }));
        jCombo_rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_ratingActionPerformed(evt);
            }
        });

        jButton_rateBook.setText("Rate Book");
        jButton_rateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rateBookActionPerformed(evt);
            }
        });

        jLabelRelease.setText("jLabel1");

        jLabelAuthor.setText("jLabel1");

        jLabelGenre.setText("jLabel1");

        jLabelAgeRating.setText("jLabel1");

        jLabelRating.setText("jLabel1");

        jLabelLanguage.setText("jLabel1");

        jTextArea_description.setEditable(false);
        jTextArea_description.setBackground(new java.awt.Color(238, 238, 238));
        jTextArea_description.setColumns(20);
        jTextArea_description.setRows(5);
        jTextArea_description.setBorder(null);
        jTextArea_description.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea_description.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea_description);

        jLabel_price.setText("Price:");

        jLabelPrice.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_return)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCombo_rating, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_rateBook)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_buyBook)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_imgLink, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_ageRating)
                                    .addComponent(jLabel_rating)
                                    .addComponent(jLabel_price)
                                    .addComponent(jLabel_language)
                                    .addComponent(jLabel_description))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelRating, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelAgeRating, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_author)
                                        .addComponent(jLabel_genre)
                                        .addComponent(jLabel_release))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabelGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelRelease, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_imgLink, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_release)
                            .addComponent(jLabelRelease))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_author)
                            .addComponent(jLabelAuthor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_genre)
                            .addComponent(jLabelGenre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ageRating)
                            .addComponent(jLabelAgeRating))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_rating)
                            .addComponent(jLabelRating))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_price)
                    .addComponent(jLabelPrice))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_language)
                    .addComponent(jLabelLanguage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_description)
                        .addGap(134, 134, 134)
                        .addComponent(jButton_return))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCombo_rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_rateBook)
                            .addComponent(jButton_buyBook))))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>                        

    private void jCombo_ratingActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jButton_rateBookActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        
        if(user.getUid().equals("0")){
            JOptionPane.showMessageDialog(null, "Please log in first.");
        }else{
            Verbindung db = new Verbindung();
            db.start();
            Connection conn = db.getVerbindung();
            Statement stmt,stmt2;
            try {
                stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM rates where uid = '"+user.getUid()+"' and mid = '"+book.getMid()+"' ");
                
                if( rs.first() ){
                    JOptionPane.showMessageDialog(null, "You have already rated this book!");
                } else {        
                    stmt2 = conn.createStatement();
                    stmt2.executeUpdate("INSERT INTO rates(uid, mid, rating) VALUES ('"+user.getUid()+"', '"+book.getMid()+"', '"+ jCombo_rating.getSelectedItem() +"') ");
                    JOptionPane.showMessageDialog(null, "Thank you for rating this book!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(BookInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                                

    private void jButton_returnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        dispose();
    }                                              

    private void jButton_buyBookActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if(user.getUid().equals("0")){
            JOptionPane.showMessageDialog(null, "Please log in first.");
        }else if(user.getPrename().equals("") || user.getSurname().equals("")|| user.getStreet().equals("")|| user.getZipcode().equals("")|| user.getCity().equals("") || user.getIban() == null || user.getBic() == null || user.getIban().equals("")|| user.getBic().equals("")){
            JOptionPane.showMessageDialog(null, "You have to change your account information and fill in all fields.");
        }else{
            try {
                new Bought(user, book).setVisible(true);
            } catch (MalformedURLException | SQLException ex) {
                Logger.getLogger(BookInfo.class.getName()).log(Level.SEVERE, null, ex);
            }

            dispose();
        }
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new bookInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_buyBook;
    private javax.swing.JButton jButton_rateBook;
    private javax.swing.JButton jButton_return;
    private javax.swing.JComboBox jCombo_rating;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAgeRating;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelGenre;
    private javax.swing.JLabel jLabelLanguage;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelRating;
    private javax.swing.JLabel jLabelRelease;
    private javax.swing.JLabel jLabel_ageRating;
    private javax.swing.JLabel jLabel_author;
    private javax.swing.JLabel jLabel_description;
    private javax.swing.JLabel jLabel_genre;
    private javax.swing.JLabel jLabel_imgLink;
    private javax.swing.JLabel jLabel_language;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JLabel jLabel_rating;
    private javax.swing.JLabel jLabel_release;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_description;
    // End of variables declaration                   
}
