/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bookrental;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.WindowConstants;

/**
 *
 * @author stefano
 */
public class Overview extends javax.swing.JFrame {

    /**
     * Creates new form RentedBookovies
     */
    public Overview() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        Verbindung db = new Verbindung();
        db.start();
        Connection conn = db.getVerbindung();

        // Amount of Users
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT count(*) as amount FROM user");
        rs.next();
        jLabel_ammountOfUser.setText(rs.getString("amount") + " Users");
        
        // Amount of active books
        Statement stmt2 = conn.createStatement();
        ResultSet rs2 = stmt2.executeQuery("SELECT count(*) as amount FROM book where bought = 1");
        rs2.next();
        jLabel_booksAktiv.setText(rs2.getString("amount") + " books");
        
        // Amount of all books
        Statement stmt3 = conn.createStatement();
        ResultSet rs3 = stmt3.executeQuery("SELECT count(*) as amount FROM book");
        rs3.next();
        jLabel_booksInaktiv.setText(rs3.getString("amount") + " books");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_overview = new javax.swing.JLabel();
        jLabel_amountBooksActiv = new javax.swing.JLabel();
        jLabel_amountOfUsers = new javax.swing.JLabel();
        jLabel_booksAktiv = new javax.swing.JLabel();
        jLabel_ammountOfUser = new javax.swing.JLabel();
        jButton_return = new javax.swing.JButton();
        jLabel_amountBooksInactiv = new javax.swing.JLabel();
        jLabel_booksInaktiv = new javax.swing.JLabel();

        jLabel_overview.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel_overview.setText("Overview");

        jLabel_amountBooksActiv.setText("Amount of books(only active): ");

        jLabel_amountOfUsers.setText("Amount of users: ");

        jLabel_booksAktiv.setText("34 Books");

        jLabel_ammountOfUser.setText("8 Books");

        jButton_return.setText("Return");
        jButton_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_returnActionPerformed(evt);
            }
        });

        jLabel_amountBooksInactiv.setText("Amount of books(with inactive): ");

        jLabel_booksInaktiv.setText("34 Books");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_overview)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_amountBooksInactiv, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_amountBooksActiv)
                                    .addComponent(jLabel_amountOfUsers))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_booksAktiv)
                                    .addComponent(jLabel_ammountOfUser)
                                    .addComponent(jLabel_booksInaktiv)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton_return)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel_overview)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_amountOfUsers)
                    .addComponent(jLabel_ammountOfUser))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_amountBooksActiv)
                    .addComponent(jLabel_booksAktiv))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_amountBooksInactiv)
                    .addComponent(jLabel_booksInaktiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton_return)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_returnActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Overview().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Overview.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_return;
    private javax.swing.JLabel jLabel_ammountOfUser;
    private javax.swing.JLabel jLabel_amountBooksActiv;
    private javax.swing.JLabel jLabel_amountBooksInactiv;
    private javax.swing.JLabel jLabel_amountOfUsers;
    private javax.swing.JLabel jLabel_booksAktiv;
    private javax.swing.JLabel jLabel_booksInaktiv;
    private javax.swing.JLabel jLabel_overview;
    // End of variables declaration//GEN-END:variables
}
