/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bookrental;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author stefano
 */
public class RentedBook extends javax.swing.JFrame {

    /**
     * Creates new form RentedBooks
     */
    public RentedBook() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Verbindung db = new Verbindung();
        db.start();
        Connection conn = db.getVerbindung();

        // Last 24 Hours
        Statement stmt = conn.createStatement();
        ResultSet rs24 = stmt.executeQuery("SELECT * FROM rents WHERE DATEDIFF(now(), time) < 1");
        rs24.last();
        jLabel_last24Hours.setText(String.valueOf(rs24.getRow()) + " Books");
        
        // Last 7 Days
        Statement stmt2 = conn.createStatement();
        ResultSet rs7 = stmt2.executeQuery("SELECT * FROM rents WHERE DATEDIFF(now(), time) < 7");
        rs7.last();
        jLabel_last7Days.setText(String.valueOf(rs7.getRow()) + " Books");
       
        // Last 30 Days
        Statement stmt3 = conn.createStatement();
        ResultSet rs30 = stmt3.executeQuery("SELECT * FROM rents WHERE DATEDIFF(now(), time) < 30");
        rs30.last();
        jLabel_last30Days.setText(String.valueOf(rs30.getRow()) + " Books");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_logo = new javax.swing.JLabel();
        jLabel_rentedBook = new javax.swing.JLabel();
        jLabel_last30D = new javax.swing.JLabel();
        jLabel_last7D = new javax.swing.JLabel();
        jLabel_last24H = new javax.swing.JLabel();
        jLabel_last30Days = new javax.swing.JLabel();
        jLabel_last7Days = new javax.swing.JLabel();
        jLabel_last24Hours = new javax.swing.JLabel();
        jButton_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jLabel_logo.setText("jLabel2");

        jLabel_rentedBook.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel_rentedBook.setText("Rented Books");

        jLabel_last30D.setText("Last 30 days:");

        jLabel_last7D.setText("Last 7 days:");

        jLabel_last24H.setText("Last 24 hours:");

        jLabel_last30Days.setText("89 Books");

        jLabel_last7Days.setText("34 Books");

        jLabel_last24Hours.setText("8 Books");

        jButton_return.setText("Return");
        jButton_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_rentedBook)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_last30D)
                                    .addComponent(jLabel_last7D)
                                    .addComponent(jLabel_last24H))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_last7Days)
                                    .addComponent(jLabel_last30Days)
                                    .addComponent(jLabel_last24Hours)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton_return))
                    .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel_rentedBook)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_last24H)
                    .addComponent(jLabel_last24Hours))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_last7D)
                    .addComponent(jLabel_last7Days))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_last30D)
                    .addComponent(jLabel_last30Days))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton_return)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_returnActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RentedBook().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RentedBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_return;
    private javax.swing.JLabel jLabel_last24H;
    private javax.swing.JLabel jLabel_last24Hours;
    private javax.swing.JLabel jLabel_last30D;
    private javax.swing.JLabel jLabel_last30Days;
    private javax.swing.JLabel jLabel_last7D;
    private javax.swing.JLabel jLabel_last7Days;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_rentedBook;
    // End of variables declaration//GEN-END:variables
}
